Repository kubevirt/monitoring, pull requests merged in 2021-12, with the labels that each got.

#60 docs, Add runbook for KubeMacPoolDown
  docs/runbooks/KubeMacPoolDown.md
  docs/runbooks/README.md
Labels: size/S, dco-signoff: yes

#61 Update KubeVirt control plane Grafana dashboard
  dashboards/grafana/kubevirt-control-plane.json
Labels: size/XXL, dco-signoff: yes

#30 Add runbook for VirtControllerRESTErrorsHigh alert
  docs/runbooks/README.md
  docs/runbooks/VirtControllerRESTErrorsHigh.md
Labels: size/S, dco-signoff: yes

#33 Add runbook for VirtControllerRESTErrorsBurst alert
  docs/runbooks/README.md
  docs/runbooks/VirtControllerRESTErrorsBurst.md
Labels: size/S, dco-signoff: yes

#34 Add runbook for VirtHandlerRESTErrorsHigh alert
  docs/runbooks/README.md
  docs/runbooks/VirtHandlerRESTErrorsHigh.md
Labels: size/S, dco-signoff: yes

#35 Add runbook for VirtHandlerRESTErrorsBurst alert
  docs/runbooks/README.md
  docs/runbooks/VirtHandlerRESTErrorsBurst.md
Labels: size/S, dco-signoff: yes

#29 Add runbook for LowVirtControllersCount alert
  docs/runbooks/LowVirtControllersCount.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#28 Add runbook for VirtControllerDown alert
  docs/runbooks/README.md
  docs/runbooks/VirtControllerDown.md
Labels: size/M, dco-signoff: yes

#63 Adjust the alert durations according to Kubevirt code
  docs/runbooks/LowVirtOperatorCount.md
  docs/runbooks/README.md
  docs/runbooks/VirtOperatorRESTErrorsBurst.md
  docs/runbooks/VirtOperatorRESTErrorsHigh.md
Labels: size/XS, dco-signoff: yes

#62 Add storageprofile incomplete alert runbook
  docs/runbooks/CDIStorageProfilesIncomplete.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#64 Improve SSPCommonTemplatesModificationReverted diagnostics
  docs/runbooks/SSPCommonTemplatesModificationReverted.md
  docs/runbooks/SSPFailingToReconcile.md
  docs/runbooks/SSPHighRateRejectedVms.md
  docs/runbooks/SSPOperatorDown.md
  docs/runbooks/SSPTemplateValidatorDown.md
Labels: size/S, dco-signoff: yes
