Repository kubevirt/monitoring, pull requests merged in 2021-11, with the labels that each got.

#55 Add monitoring guidelines
  monitoring-guidelines.md
Labels: size/M, dco-signoff: yes

#27 Add runbook for NoReadyVirtController alert
  docs/runbooks/NoReadyVirtController.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#26 Add runbook for LowReadyVirtControllersCount alert
  docs/runbooks/LowReadyVirtControllersCount.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#24 Add runbook for LowVirtAPICount alert
  docs/runbooks/LowVirtAPICount.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#59 Fix typo in title
  docs/runbooks/KubeVirtComponentExceedsRequestedMemory.md
Labels: size/XS, dco-signoff: yes

#56 Add initial 3 CDI alert runbooks
  docs/runbooks/CDIDataVolumeUnusualRestartCount.md
  docs/runbooks/CDINotReady.md
  docs/runbooks/CDIOperatorDown.md
  docs/runbooks/README.md
Labels: size/L, dco-signoff: yes

#57 Add initial HPP alert runbooks
  docs/runbooks/HPPNotReady.md
  docs/runbooks/HPPOperatorDown.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes
