Repository kubevirt/monitoring, pull requests merged in 2021-08, with the labels that each got.

#15 Move runbooks to docs directory
  docs/KubeVirtComponentExceedsRequestedCPU.md
  docs/KubeVirtComponentExceedsRequestedMemory.md
  docs/KubevirtHyperconvergedClusterOperatorCRModification.md
  docs/KubevirtHyperconvergedClusterOperatorUSModification.md
  docs/KubevirtVmHighMemoryUsage.md
  docs/LowKVMNodesCount.md
  docs/OrphanedVirtualMachineImages.md
  docs/OutdatedVirtualMachineInstanceWorkloads.md
  docs/README.md
  docs/VMCannotBeEvicted.md
  docs/VirtAPIDown.md
Labels: dco-signoff: yes, size/XS

#16 Move runbooks from docs to docs/runbooks
  docs/runbooks/KubeVirtComponentExceedsRequestedCPU.md
  docs/runbooks/KubeVirtComponentExceedsRequestedMemory.md
  docs/runbooks/KubevirtHyperconvergedClusterOperatorCRModification.md
  docs/runbooks/KubevirtHyperconvergedClusterOperatorUSModification.md
  docs/runbooks/KubevirtVmHighMemoryUsage.md
  docs/runbooks/LowKVMNodesCount.md
  docs/runbooks/OrphanedVirtualMachineImages.md
  docs/runbooks/OutdatedVirtualMachineInstanceWorkloads.md
  docs/runbooks/README.md
  docs/runbooks/VMCannotBeEvicted.md
  docs/runbooks/VirtAPIDown.md
Labels: dco-signoff: yes, size/XS

#17 List the runbooks in the pages site
  .github/workflows/generate_index.yaml
  automation/generate_pages_index.py
  docs/index.md
  docs/runbooks/README.md
Labels: dco-signoff: yes, size/M

#19 runbooks, Add CnaoNotReady alert
  docs/runbooks/CnaoNotReady.md
  docs/runbooks/README.md
Labels: dco-signoff: yes, size/M

#21 runbooks, Add info on CnaoNotReady runbook
  docs/runbooks/CnaoNotReady.md
Labels: size/XS, dco-signoff: yes

#18 runbooks, Add CnaoDown Alert
  docs/runbooks/CnaoDown.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#22 runbooks, rename CnaoNotReady alert to NetworkAddonsConfigNotReady
  docs/runbooks/NetworkAddonsConfigNotReady.md
  docs/runbooks/README.md
Labels: size/XS, do-not-merge/hold, dco-signoff: yes

#25 Fix typo
  docs/runbooks/KubeVirtComponentExceedsRequestedCPU.md
Labels: size/XS, dco-signoff: yes

#14 Update top consumers dashboard based on OCP limitations
  dashboards/kubevirt-top-consumers.json
Labels: size/XL, dco-signoff: yes

#31 Add memory rss panels to to consumers dashboard
  dashboards/kubevirt-top-consumers.json
Labels: size/L, dco-signoff: yes

#32 Update memory panels in top consumers dashboard
  dashboards/kubevirt-top-consumers.json
Labels: size/S, dco-signoff: yes

#23 runbooks, Add info about KubeMacPoolDuplicateMacsFound runbook
  docs/runbooks/KubeMacPoolDuplicateMacsFound.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#36 Update Top consumers dashboard titles
  dashboards/kubevirt-top-consumers.json
Labels: size/M, dco-signoff: yes
