Repository kubevirt/monitoring, pull requests merged in 2021-09, with the labels that each got.

#38 [Sig-Scale] dashboard: add kubevirt control plane dashboard
  dashboards/grafana/kubevirt-control-plane.json
Labels: size/XXL, dco-signoff: yes

#40 Move top consumers dashboard to openshift sub folder
  dashboards/openshift/kubevirt-top-consumers.json
Labels: size/XS, dco-signoff: yes

#41 Add OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: size/S, dco-signoff: yes

#47 drop fancy Unicode quote to make example pastable
  docs/runbooks/OutdatedVirtualMachineInstanceWorkloads.md
Labels: size/XS, dco-signoff: yes
