Repository kubevirt/monitoring, pull requests merged in 2021-05, with the labels that each got.

#7 Make VirtAPIDown environment agnostic
  runbooks/VirtAPIDown.md
Labels: dco-signoff: yes, size/S

#8 add runbook for outdated vmi workloads alert
  runbooks/OutdatedVirtualMachineInstanceWorkloads.md
Labels: dco-signoff: yes, size/M

#9 Update component_name label for KubevirtHyperconvergedClusterOperatorCRModification
  runbooks/KubevirtHyperconvergedClusterOperatorCRModification.md
Labels: dco-signoff: yes, size/XS
