Repository kubevirt/monitoring, pull requests merged in 2022-05, with the labels that each got.

#84 Add new runbook: KubevirtHyperconvergedClusterOperatorInstallationNot…
  docs/runbooks/KubevirtHyperconvergedClusterOperatorInstallationNotCompletedAlert.md
  docs/runbooks/README.md
Labels: size/S, dco-signoff: yes

#86 Delete KubevirtVmHighMemoryUsageBasedOnRequests runbook
  docs/runbooks/KubevirtVmHighMemoryUsageBasedOnRequests.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: no

#82 Add runbook explaining CnaoNmstateMigration alert
  docs/runbooks/CnaoNmstateMigration.md
  docs/runbooks/README.md
Labels: size/S, dco-signoff: yes

#87 Add priority and infra_alert labels
  monitoring-guidelines.md
Labels: size/XS, dco-signoff: yes

#88 Add runbook for KubevirtHyperconvergedClusterOperatorNMOInUseAlert
  docs/runbooks/KubevirtHyperconvergedClusterOperatorNMOInUseAlert.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#85 Add a Runbook for KubeVirtVMIExcessiveMigrations alert
  docs/runbooks/KubeVirtVMIExcessiveMigrations.md
  docs/runbooks/KubevirtHyperconvergedClusterOperatorInstallationNotCompletedAlert.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes
