Repository kubevirt/monitoring, pull requests merged in 2022-01, with the labels that each got.

#66 Update OrphanedVirtualMachineImages alert name
  docs/runbooks/OrphanedVirtualMachineInstances.md
  docs/runbooks/README.md
Labels: size/S, dco-signoff: yes

#67 Add DataImportCron outdated alert runbook
  docs/runbooks/CDIDataImportCronOutdated.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#69 Add a runbook for KubevirtVmHighMemoryUsageBasedOnRequests
  docs/runbooks/KubevirtVmHighMemoryUsageBasedOnRequests.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#68 Added new labels required for alerts
  monitoring-guidelines.md
Labels: size/S, dco-signoff: yes

#70 Update the Top Consumers dashboard
  dashboards/openshift/kubevirt-top-consumers.json
Labels: size/XL, dco-signoff: yes
