Repository kubevirt/monitoring, pull requests merged in 2022-02, with the labels that each got.

#71 Remove Erkan from Owners
  OWNERS_ALIASES
Labels: size/XS, dco-signoff: yes

#76 Add GitHub Action to keep metrics documentation file updated
  .github/workflows/update_metrics_docs.yaml
Labels: size/M, dco-signoff: yes

#75 Add HPP sharing pool path with OS runbook
  docs/runbooks/HPPSharingPoolPathWithOS.md
  docs/runbooks/README.md
Labels: size/M, dco-signoff: yes

#79 Correct typo in HPPSharingPoolPathWithOS runbook
  docs/runbooks/HPPSharingPoolPathWithOS.md
Labels: size/XS, dco-signoff: yes

#77 Fix issues in the monitoring-guideline document
  monitoring-guidelines.md
Labels: size/M, dco-signoff: yes

#78 Add a note for CDIDataImportCronOutdated in disconnected enviroments
  docs/runbooks/CDIDataImportCronOutdated.md
Labels: size/S, dco-signoff: yes

#80 Fix issues in top consumers dashboard
  dashboards/openshift/kubevirt-top-consumers.json
Labels: size/S, dco-signoff: yes
