Repository kubevirt/monitoring, pull requests merged in 2023-06, with the labels that each got.

#178 Rename KubeVirtDeprecatedAPIRequested to singular
  docs/runbooks/KubeVirtDeprecatedAPIRequested.md
  docs/runbooks/README.md
Labels: size/XS, dco-signoff: yes

#179 Add metrics parser to metricFamily for prom-metrics-linter
  test/metrics/prom-metrics-linter/metrics-parser/go.mod
  test/metrics/prom-metrics-linter/metrics-parser/go.sum
  test/metrics/prom-metrics-linter/metrics-parser/metrics_parser.go
Labels: size/M, dco-signoff: yes

#180 Add tags to metric name linter
  .github/workflows/prom-metrics-linter.yaml
Labels: size/S, dco-signoff: yes
