Repository kubevirt/monitoring, pull requests merged in 2024-07, with the labels that each got.

#255 Improve CDI alert runbooks clarity
  docs/runbooks/CDIDataImportCronOutdated.md
  docs/runbooks/CDIDefaultStorageClassDegraded.md
  docs/runbooks/CDINoDefaultStorageClass.md
Labels: size/S, dco-signoff: yes

#254 Add public copyright license
  LICENSE
  monitoringlinter/analyzer.go
  monitoringlinter/analyzer_test.go
  monitoringlinter/cmd/monitoringlinter/main.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/no_import.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/no_local_name.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/no_registration.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/operatorobservability/with_local_name.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/no_import.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/no_local_name.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/no_registration.go
  monitoringlinter/testdata/src/a/testrepo/pkg/controller/prometheus/with_local_name.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/no_import.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/no_local_name.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/no_registration.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/operatorobservability/with_local_name.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/no_import.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/no_local_name.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/no_registration.go
  monitoringlinter/testdata/src/a/testrepo/pkg/monitoring/prometheus/with_local_name.go
  tools/metricsdocs/git.go
  tools/metricsdocs/metricsdocs.go
  tools/metricsdocs/types.go
  tools/runbook-sync-downstream/commitdate.go
  tools/runbook-sync-downstream/main.go
  tools/runbook-sync-downstream/runbook.go
  tools/runbook-sync-downstream/setup.go
  tools/runbook-sync-downstream/worktree.go
Labels: size/XL, dco-signoff: yes

#257 CNV-41549 - Fixing a diagnosis step for CDIDefaultStorageClassDegraded
  docs/runbooks/CDIDefaultStorageClassDegraded.md
Labels: size/XS, dco-signoff: yes
